### ISSUE TITLE
Can't fetch UUID

### ISSUE THREAD

**Issue by AeSix** [ironboundred/AdvancedBan#10]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 https://github.com/ironboundred/AdvancedBan/tree/v3.0.11-SNAPSHOT(2)
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord
 
_What server version (/version) are you using?_
BungeeCord version git:BungeeCord-Bootstrap:1.14-SNAPSHOT:5c6bc18:1418 by md_5

_Please provide the EXACT steps required to reproduce the problem..._
1. Removed AB 2.1.6 (Leoko's) 
2. installed this version
3. started Bungee
4. attempted to connect
5. received "Failed to fetch UUID" on client screen
6. checked console, seen issue, opened ticket. 

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
```
09:35:44 [INFO] [/<redacted>:65151] <-> InitialHandler has connected
09:35:45 [INFO] Error -> Server returned HTTP response code: 400 for URL: https://api.mojang.com/users/profiles/minecraft/lost_hopee?at=%TIMESTAMP%
09:35:45 [INFO] !! Failed fetching UUID of lost_hopee
09:35:45 [INFO] !! Could not connect to REST-API under https://api.mojang.com/users/profiles/minecraft/%NAME%?at=%TIMESTAMP%
09:35:45 [INFO] Trying to fetch UUID form BackUp-API...
09:35:45 [INFO] !! Failed fetching UUID of lost_hopee
09:35:45 [INFO] !! Could not find key 'uuid' in the servers response
09:35:45 [INFO] !! Response: OK
09:35:45 [INFO] !! !! Warning we have not been able to fetch the UUID of the Player lost_hopee
09:35:45 [INFO] !! Make sure that the name is spelled correctly and if it is change your UUID-Fetcher settings!
```
_Add any additional information below._
I'm able to help test some, but life may become busy for me soon meaning I won't be quick to respond.  Additionally, I can do changes in the early mornings, as few players are on at that time.

**Comment by ironboundred** [comment]
Seems I removed the ?at=%TIMESTAMP% replacments code for fetching uuids if you change your config and remove that from the url it will work untill i can fix it

**Comment by ironboundred** [comment]
Newest release has this fixed https://github.com/ironboundred/AdvancedBan/releases/tag/v3.0.13-SNAPSHOT

**Comment by AeSix** [comment]
lol, thanks! I didn't even get around to updating the config :P 
Seriously, Thank you for the effort! :)
