### ISSUE TITLE
mysql.toml is empty after generation

### ISSUE THREAD

**Issue by MalTeeez** [ironboundred/AdvancedBan#2]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 3.0.6
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Velocity - Paper
 
_What server version (/version) are you using?_
1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1.Turn on MySql in cofig.toml
2.Restart Proxy
3.mysql.toml is empty
_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
It doesnt generate any errors.
_Add any additional information below._
For now just paste https://github.com/ironboundred/AdvancedBan/blob/master/AdvancedBan-Velocity/src.main.resources/MySQl.toml into your .toml as a fix.

**Comment by ironboundred** [comment]
The name of the resource it's trying to copy is MySQL.toml and the code has it trying to copy mysql.toml, simple fix.
